"""empty message

Revision ID: 751cdfec3eda
Revises: 558cee33edfe
Create Date: 2026-02-24 23:24:18.446082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '751cdfec3eda'
down_revision: Union[str, Sequence[str], None] = '558cee33edfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cameras_room_id_fkey'), 'cameras', type_='foreignkey')
    op.drop_constraint(op.f('cameras_edge_node_id_fkey'), 'cameras', type_='foreignkey')
    op.create_foreign_key(None, 'cameras', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cameras', 'edge_nodes', ['edge_node_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('face_embeddings_person_id_fkey'), 'face_embeddings', type_='foreignkey')
    op.create_foreign_key(None, 'face_embeddings', 'persons', ['person_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('rooms_building_id_fkey'), 'rooms', type_='foreignkey')
    op.create_foreign_key(None, 'rooms', 'buildings', ['building_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.create_foreign_key(op.f('rooms_building_id_fkey'), 'rooms', 'buildings', ['building_id'], ['id'])
    op.drop_constraint(None, 'face_embeddings', type_='foreignkey')
    op.create_foreign_key(op.f('face_embeddings_person_id_fkey'), 'face_embeddings', 'persons', ['person_id'], ['id'])
    op.drop_constraint(None, 'cameras', type_='foreignkey')
    op.drop_constraint(None, 'cameras', type_='foreignkey')
    op.create_foreign_key(op.f('cameras_edge_node_id_fkey'), 'cameras', 'edge_nodes', ['edge_node_id'], ['id'])
    op.create_foreign_key(op.f('cameras_room_id_fkey'), 'cameras', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###
